name: geog0111
channels:
  - conda-forge
  - defaults
dependencies:
  - pyephem
  - tensorflow
  - git
  - python>=3.7
  - nomkl
  - libgdal
  - geopandas
  - rasterio
  - scipy
  - gdal
  - beautifulsoup4
  - fiona
  - numpy
  - statsmodels
  - cartopy
  - scikit-image
  - netcdf4
  - scikit-learn
  - matplotlib-base
  - matplotlib
  - pandas
  - ipython
  - numpydoc
  - astropy
  - shapely
  - ipyleaflet
  - pytest
  - seaborn
  - hdf5
  - flake8
  - ipywidgets
  - xarray
  - black
  - folium
  - jupyter_console
  - jupyter_contrib_nbextensions
  - pandocfilters
  - nbconvert
  - jupyterlab
  - pandoc
  - pyephem
  - libnetcdf
  - ipykernel
  - ipympl
  - pip
  - yapf
  - autopep8
  - geemap
  - jupyter
  - nbgitpuller
  - mkdocs
  - pycodestyle
  - sphinx
  - fsspec
  - xlrd
  - git-lfs
  - ipywidgets
  - pip:
    - nbsphinx
    - mkdocs-jupyter
    - urlpath
    - mknotebooks
    - mkdocs-material
    - mkdocs-exclude
    - mkdocs-git-revision-date-localized-plugin
    - recommonmark
    - sphinx-markdown-tables
    - sphinx-typlog-theme
    - mkdocs-rtd-dropdown
    - mkdocs-material
    - astropy
    - xlrd
    - pyephem
    - netCDF4
    - numpydoc
# conda env update -f environment.yml
# python -m ipykernel install --name=conda-env-geog0111-geog0111-py --display-name 'conda env:geog0111-geog0111'
